### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by sapid** [BruceJillis/ModJam4#2]
Hey, I noticed there's no license on this. I'd love to include it in my modpack once you fix #1 - there don't seem to be any forge mods like it; anything similar is a Bukkit plugin. (RIP Bukkit.) 

What's your stance on redistributing your mod as part of a pack?

**Comment by BruceJillis** [comment]
I'm very sorry.. I tried to get it into a better shape recently but im afraid its just gonna take too much time. If the modpack is singleplayer only it could work but im afraid even the model is not rendering in the correct position..

So in short, im going to leave this mod in the current non-functional state (I will update the readme to reflect that).
